artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/idAryan/Book-Recommender-System/raw/refs/heads/master/archive.zip
  raw_data_dir: raw_data
  ingested_dir: ingested_data

data_validation_config:
  validation_status_file: validation_report.yaml
  required_files:
    - books.csv
    - ratings.csv
